services:
  frontend:
    container_name: test_frontend
    build: .
    ports:
      - "8200:80"
    expose:
      - 80
      - 16
    networks:
      - db-network

networks:
  db-network:
    external: true
